services:
    traefik:
        image: traefik:2.3
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            ferror:
                ipv4_address: 192.168.10.2

    symfony:
        image: ferror/symfony-image:7.4
        command: ["make", "run"]
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.symfony.rule=Host(`symfony.malcherczyk.localhost`)"
        volumes:
            - ./:/app:delegated
        networks:
            - ferror

    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_PASSWORD: 1234
        volumes:
            - ./database/postgres:/docker-entrypoint-initdb.d:delegated
        ports:
            - "5432:5432"
        depends_on:
            - traefik
        networks:
            - ferror

networks:
    ferror:
        name: ferror
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.10.0/24
